baseURL = "http://smartvistos.com.br"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Smart Vistos"
[markup.goldmark.renderer]
unsafe = true
