[de]
contentDir = ""
copyright = ""
footer_content = ""
footer_menu_left = ""
footer_menu_middle = ""
footer_menu_right = ""
languageName = ""
title = ""
weight = ""
[en]
contentDir = "content/english"
copyright = "© Copyright 2024 Smart Vistos. Todos os direitos reservados. <br>Cópia do código de conduta dos agentes de imigração do [OMARA](https://www.mara.gov.au/tools-for-registered-agents/code-of-conduct).<br>Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"
footer_content = ""
footer_menu_left = "Vistos AUS"
footer_menu_middle = "Empresa"
footer_menu_right = "Contato"
languageName = ""
title = "Imigração para Austrália"
weight = 1
