[[footer_left]]
name = "General Skilled Migration"
url = "https://www.smartvistos.com.br/vistos/profissionais-qualificados"
[[footer_left]]
name = "Global Talent visa"
url = "#"
[[footer_left]]
name = "Partner visas"
url = "https://www.smartvistos.com.br/vistos/partner-visas"
[[footer_middle]]
name = "Registered Migration Agent"
url = "https://www.smartvistos.com.br/agente-de-imigracao/"
[[footer_middle]]
name = "Quem somos"
url = "https://www.smartvistos.com.br/empresa/"
[[footer_middle]]
name = "Equipe"
url = "https://smartvistos.com.br/equipe/"
[[footer_right]]
name = "Entrevista Inicial"
url = "https://smartvistos.com.br/contato/"
[[footer_right]]
name = "Endereço comercial"
url = "https://smartvistos.com.br/contato/"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Vistos"
url = "vistos "
weight = 3
[[main]]
name = "Empresa"
url = "empresa"
weight = "4"
[[main]]
name = "Depoimentos"
url = "depoimentos"
weight = "5"
[[main]]
name = "Blog"
url = "https://smartvistos.net.br/"
weight = "6"
[[main]]
name = "Contato"
url = "contato"
weight = "7"
