[[footer_left]]
name = "Quem somos"
url = "https://smartvistos.netlify.app/empresa/"
[[footer_left]]
name = "Equipe"
url = "https://smartvistos.netlify.app/equipe/"
[[footer_left]]
name = "Agente de Imigração"
url = "https://smartvistos.netlify.app/agente-de-imigracao/"
[[footer_middle]]
name = "General Skilled Migration"
url = "#"
[[footer_middle]]
name = "Global Talent visa"
url = "#"
[[footer_middle]]
name = "Partner visas"
url = "#"
[[footer_right]]
name = "Política de privacidade"
url = "privacy-policy"
[[footer_right]]
name = "Telefone"
url = "faq"
[[footer_right]]
name = "Endereço comercial"
url = "terms-conditions"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Vistos"
url = "vistos "
weight = 3
[[main]]
name = "Empresa"
url = "empresa"
weight = "4"
[[main]]
name = "Depoimentos"
url = "depoimentos"
weight = "5"
[[main]]
name = "Contato"
url = "contato"
weight = "6"
